import React from 'react'
import type { Metadata } from "next";

import { Toaster } from '@/components/ui/sonner';

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <main>{children}</main>
                <Toaster/>
            </body>
        </html>
    )
}

export default RootLayout
